openapi: 3.0.3
info:
  title: WalletAPI -> SysDucash

  version: 1.0.11

servers:
  - url: https://api-sysducash.ducash.com.br/api/v1
tags:
  - name: parceiros
paths:
  /parceiros:
    get:
      tags:
        - Parceiros
      summary: Lista parceiros
      description: Retorna uma lista de parceiros baseada em um filtro
      parameters:
        - in: query
          name: lat
          description: Latitude da cidade
          required: false
          schema:
            type: number
        - in: query
          name: lng
          description: Longitude da cidade
          required: false
          schema:
            type: number
        - in: query
          name: page
          description: Pagina da lista dos objetos
          required: false
          schema:
            type: integer
        - in: query
          name: size
          description: O tamanho da lista de objetos
          required: false
          schema:
            type: integer
        - in: query
          name: city
          description: O ID (IBGE) da cidade
          required: false
          schema:
            type: integer
        - in: query
          name: state
          description: A Sigla do estado do parceiro
          required: false
          schema:
            type: string
        - in: query
          name: segmento
          description: Id do segmento dos parceiros
          schema:
            type: integer
        - in: query
          name: name
          description: Nome do parceiro
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ParceirosPaginado"
  /parceiros/register:
    post:
      tags:
        - parceiros
      operationId: CreatePartnerUser
      parameters:
        - name: cnpj
          in: query
          description: string contendo o objeto com o CNPJ do parceiro
          required: true
          explode: false
          schema:
            type: string
            default: { cnpj: XXX. XXX/0001-XX }
      responses:
        "200":
          description: Successful operation
  /parceiros/lista:
    get:
      tags:
        - Parceiros
      summary: Lista parceiros
      description: Retorna uma lista de parceiros baseada em um filtro
      parameters:
        - in: query
          name: segmento
          description: Ids dos parceiros a serem listados
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ParceirosListado"
components:
  schemas:
    ParceirosPaginado:
      type: object
      properties:
        perPage:
          type: integer
        page:
          type: integer
        total:
          type: integer
        lastPage:
          type: integer
        data:
          type: array
          items:
            $ref: "#/components/schemas/Parceiro"
    ParceirosListado:
      type: object
      properties:
        Data:
          type: array
          items:
            $ref: "#/components/schemas/Parceiro"
    Parceiro:
      type: object
      required:
        [
          Id,
          Cnpj,
          IdCompany,
          Name,
          Logo,
          HomePosition,
          HasLimit,
          Active,
          PartnerNetwork,
          DiscountPolicy,
          PartnerSite,
          IdSegment,
          Special,
          IsFavorite,
          PayWithDucash,
          City,
          DiscountFilter,
        ]
      properties:
        Id:
          type: integer
        Cnpj:
          type: string
        IdCompany:
          type: integer
        Name:
          type: string
        Logo:
          type: string
        HomePosition:
          type: integer
        HasLimit:
          type: boolean
        Active:
          type: boolean
        PartnerNetwork:
          type: boolean
        DiscountPolicy:
          type: string
        PartnerSite:
          type: string
        IdSegment:
          type: integer
        Discount:
          type: integer
        Distance:
          type: integer
        Special:
          type: boolean
        IsFavorite:
          type: boolean
        PayWithDucash:
          type: boolean
        City:
          type: string
        DiscountFilter:
          type: string
  requestBodies:
    Partner:
      description: CNPJ do parceiro
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Partner"
